### ISSUE TITLE
Replace Spray with Akka HTTP

### ISSUE THREAD

**Issue by cory-p-oncota** [kamon-io/kamon-influxdb#1]
As part of getting a 2.12 release in place, I think it'd be best to swap out Spray in favor of Akka HTTP since Spray is at end-of-life and Kamon primarily uses Akka as its only backbone across the modules.

I have a WIP branch but would like to hear input from the community on this change.

**Comment by dpsoft** [comment]
@pimeys ping!!. I thinks that is a good idea and also we can take a look to https://github.com/AsyncHttpClient/async-http-client

**Comment by pimeys** [comment]
I have a bit of time now, maybe I could refactor this!

**Comment by dpsoft** [comment]
@pimeys awsome!!

**Comment by pimeys** [comment]
@cory-p-oncota Do you have a link for your WIP branch and how far are you in refactoring the Http code to use akka-http? I had a quick look and it's almost a drop-in replacement in the influx module... Although my scala is getting quite rusty, it's been a while :)

**Comment by cory-p-oncota** [comment]
@pimeys unfortunately, I don't know where this work has gone (luckily, only about ten minutes of hacking around)

Since I only use this module in development, I shifted to working on some of the other modules when I hit an issue on [this line](https://github.com/kamon-io/kamon-influxdb/blob/master/src/main/scala/kamon/influxdb/InfluxDBMetricsPacker.scala#L33), where it appears Akka IO cannot derive an `ActorRef` from Akka HTTP in the same way it could from Spray.

It did get me thinking that a refactor of this based on streams and the host-level akka-http API would simplify much of this but that does break from the pattern I've seen in Kamon modules to depend only on akka core components.

Hopefully that's at least a bit helpful.

**Comment by pimeys** [comment]
Uh, I'm sorry for late response, but I've been very badly sick this week. Now I'm getting better and I hope I can go back to work on Monday. I did one working iteration with akka-http, and while it worked, making the tests work was a bit of a pain. You can't do stuff like `IO(Http)` and I'm not working with Scala so much anymore that I can easily see the right path with the new library. Of course I should use streams, but that feels a bit overkill here without the whole Kamon infrastructure supporting them with allowing us to deal with the back pressure.

So I'm using akka-http as a simple client, but I will not do a PR until I'm happy with my tests. :)

**Comment by pimeys** [comment]
@cory-p-oncota A stupid question: what is exactly the reason we want to switch to akka-http? Spray is well-tested and works. It's an HTTP client used by lots of instances and I don't see it having any serious security issues in the future.

Of course it would be fun to refactor the whole Kamon project to use akka-streams, but is it worth the trouble?

**Comment by ivantopo** [comment]
The thing is that there is no (and wont be) Spray build for Scala 2.12. So we need to do some changes in order to keep it building. I'm actually thinking more of async-http-client rather than akka-http, not because I have any issues with akka-http, but because we could just use the same code in the reporting modules regardless of the Akka/Scala version chosen by the users.

**Comment by cory-p-oncota** [comment]
I'm sold on async-http-client, especially due to eliminating the mess of maintaining an Akka/Scala build matrix. How can we handle the TCP functionality in that case?

**Comment by ivantopo** [comment]
the UDP part of the reporter could be handled with Netty, I got this quite some time ago: https://github.com/nilsga/Kamon/commit/0929caaa4828d1db93e94672d133d39ec27b9af8

that might work as some starting point.

**Comment by pimeys** [comment]
Ok, so the HTTP part with AsyncHTTPClient is done and tested here:

https://github.com/kamon-io/kamon-influxdb/pull/2

Of course I didn't test this in action, just got the tests green. We're mostly using Prometheus now instead of InfluxDB, so I might need a test app to try it out...

I'll take a look into the UDP in another PR.

**Comment by artursoler** [comment]
What's the status of this issue? Since PR #2 was merged, is there anything else blocking the Scala 2.12 release?

**Comment by dpsoft** [comment]
@ArturSoler I've just released the 0.6.5 version that supports scala 2.12, please add `resolvers += Resolver.bintrayRepo("kamon-io", "releases")
`

**Comment by artursoler** [comment]
Thanks!
