### ISSUE TITLE
Unable to use influxdb with SSL

### ISSUE THREAD

**Issue by anarwal27** [kamon-io/kamon-influxdb#14]
I had working solution with local deployment of influxdb and setting done via application.conf. However now I have deployed influxdb in secured container which uses https for communication, I get an error for https not supported by kamon:

```
[ERROR] [10/02/2017 09:31:04.235] [kamon-akka.actor.default-dispatcher-2] [akka://kamon/user/influxdb-metrics-sender] Protocol https is not supported by Kamon InfluxDB Client
akka.actor.ActorInitializationException: akka://kamon/user/influxdb-metrics-sender: exception during creation
```
followed by
```
Caused by: java.lang.UnsupportedOperationException: Protocol https is not supported by Kamon InfluxDB Client
```
Here is my configuration:
```
kamon {

  metric {
      tick-interval = 10 second
  }

  influxdb {
    hostname = "influxdb.foo.com"
    max-packet-size = 1024
    database = "mydb"
    protocol = "https"

    application-name = "foo-service"
    hostname-override = foo

    percentiles = [50.0, 70.5]
  }

  modules {
    kamon-log-reporter.auto-start = yes
    kamon-influxdb.auto-start = yes
  }

  trace {
      level-of-detail = simple-trace
    }

}

```

**Comment by anarwal27** [comment]
@dpsoft Can you verify if https is supported by kamon-influxdb or not?

**Comment by dpsoft** [comment]
@anarwal27 `https` is not supported https://github.com/kamon-io/kamon-influxdb/blob/ed90652e45e1241a5dce7f1ec1f1585bced6ae68/src/main/scala/kamon/influxdb/InfluxDBMetricsPacker.scala#L35-L42

**Comment by dsolonenko** [comment]
@dpsoft is it just a matter of adding "https" case or some additional configuration is required for the underlying http client?

**Comment by dpsoft** [comment]
@anarwal27 @dsolonenko I think that is only add a new case but I'm not sure. As always PR are welcome ;)

**Comment by dsolonenko** [comment]
@dpsoft Please take a look https://github.com/kamon-io/kamon-influxdb/pull/16 
Tested with my InfluxDB HTTPS setup
