### ISSUE TITLE
Support for Kamon 1.x

### ISSUE THREAD

**Issue by TimSoethout** [kamon-io/kamon-influxdb#17]
It would be nice to upgrade to Kamon 1.x, but I am using this reporter which still required Kamon 6.7.x.

**Comment by jakubmarton** [comment]
There is a branch https://github.com/kamon-io/kamon-influxdb/tree/upgrade-to-1.0 but it was updated almost a month ago. But the commit in there looks pretty big - maybe we can have it released soon? :) (pretty please)

**Comment by gianlo** [comment]
Is there any progress on this one? We've moved our service to scala 2.12 with the advent of kamon 1.0.1, but we're using influxdb for metrics, so currently we don't have metrics...

**Comment by ivantopo** [comment]
Hey people! The efforts on the branch above are the latest we have. I really would like to get this out ASAP but time is running short :(.. If you want to give it a try, there is a snapshot of that branch here: https://bintray.com/kamon-io/snapshots/kamon-influxdb/1.0.0-4fa32c762f33782653476e7e530a93b2bb08a4c3

Hopefully this will be closed pretty soon!

**Comment by mwz** [comment]
+1

**Comment by TimSoethout** [comment]
I think this is done right?
