### ISSUE TITLE
Authentication no-longer works

### ISSUE THREAD

**Issue by pawelgrzes** [kamon-io/kamon-influxdb#21]
It seems that configuration like the following:

```
kamon {
  influxdb {

    authentication {
      user = "my-user",
      password = "my-password"
    }
  }
}
```

No longer works.
I guess there is missing configuration of Authenticator when building the client:
https://github.com/kamon-io/kamon-influxdb/blob/master/src/main/scala/kamon/influxdb/InfluxDBReporter.scala#L136

**Comment by pawelgrzes** [comment]
Actually I have found a workaround :)
```
kamon {
  influxdb {
   database = "my-db&u=my-user&p=my-password"
  }
}

```
It is ugly hack, but it works ;)

**Comment by Qthunder** [comment]
https://github.com/kamon-io/kamon-influxdb/pull/25
