### ISSUE TITLE
Make InfluxDBReporter#buildClient() protected so applications can configure the http client

### ISSUE THREAD

**Issue by martin-g** [kamon-io/kamon-influxdb#28]
As reported at https://github.com/kamon-io/kamon-influxdb/issues/22#issuecomment-409927560 at the moment it is not possible to use SSL client certificates.
Please make kamon.influxdb.InfluxDBReporter#buildClient() `protected`.
Thanks!

**Comment by dpsoft** [comment]
@martin-g `kamon.influxdb.InfluxDBReporter#buildClient()` is `protected`: https://github.com/kamon-io/kamon-influxdb/blob/master/src/main/scala/kamon/influxdb/InfluxDBReporter.scala#L135

**Comment by martin-g** [comment]
Oops! It seems this was part of the merged PR and I didn't notice it! Then everything is fine! Thank you!
